sudo: required

services:
  - docker

before_install:
  - docker build -t mrkotte/visitorapp ./visitorapp

script:
    #Run tests instead of starting the server
  - docker run mrkotte/visitorapp npm test

after_success:
  - docker build -t mrkotte/visitorapp-nginx ./nginx

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take above build images and push them to docker hub
  - docker push mrkotte/visitorapp
  - docker push mrkotte/visitorapp-nginx

  deploy:
    provider: elasticbeanstalk
    region: eu-north-1
    app: docker-multi-visit
    env: DockerMultiVisit-env
    bucket_name: elasticbeanstalk-eu-north-1-679022722124
    bucket_path: docker-multi-visit
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY